### ISSUE TITLE
Undefined behavior in grid2D --> cartographer crashes frequently

### ISSUE THREAD

**Issue by oneattosecond** [ros2/cartographer#11]
Seeing a regular crash in cartographer (every 30-60 seconds) when compiling with an alternate compiler (e.g. LLVM), this makes it very difficult to actually map a room.

The crash occurs in Submap2D::Finish(), which calls grid_ComputeCroppedGrid() which calls common::make_unique<ProbabilityGrid>, as part of this call, one of the standard libs is doing a release and delete of a derived class

It appears to be a case of UB as described in https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP52-CPP.+Do+not+delete+a+polymorphic+object+without+a+virtual+destructor

I confirmed the crash no longer occurs when fixing the UB by adding a default virtual destructor to Grid2D()

**Comment by clalancette** [comment]
> I confirmed the crash no longer occurs when fixing the UB by adding a default virtual destructor to Grid2D()

Thanks for reporting.  This project is essentially a build-system-only port of cartographer to ROS 2.  As such, there are no actual code changes here.  Any issues you find with the code are better reported to the upstream: https://github.com/googlecartographer/cartographer .  I'm going to close this for now, but feel free to comment or re-open if needed.
