### ISSUE TITLE
arm64 Foxy build failing

### ISSUE THREAD

**Issue by emersonknapp** [ros2/cartographer#17]
This package has been bloomed into Foxy, but the arm64 build is failing

Latest build as of this reporting: http://build.ros2.org/view/Fbin_ubv8_uFv8/job/Fbin_ubv8_uFv8__cartographer__ubuntu_focal_arm64__binary/13/

It appears to fail because libceres-dev is not present on Focal on arm64. I've reported the issue with it 
* On the source project https://github.com/ceres-solver/ceres-solver/issues/599
* On the ubuntu packaging https://bugs.launchpad.net/ubuntu/+source/ceres-solver/+bug/1882626

Opening the report to track that information.

**Comment by clalancette** [comment]
Yes, I have a PR open to blacklist cartographer on arm64: https://github.com/ros2/ros_buildfarm_config/pull/101 .  Unless Ubuntu decides to release libceres-dev for arm64, there isn't much we can do here.

**Comment by emersonknapp** [comment]
We can influence the re-release, yeah? SLAM-Toolbox depends on libceres as well, so if we don't take any action, we're pretty much screwed on SLAM for arm64.

**Comment by emersonknapp** [comment]
I'm working on hunting down the patch to fix the 1.14.x version of ceres-solver for ARM so that we can get it into the Ubuntu SRU process - I'll keep this ticket updated with any progress

**Comment by clalancette** [comment]
We got this working ages ago, thanks to the work from @emersonknapp .  Closing.
