### ISSUE TITLE
how can i build cartographer_ros with foxy？

### ISSUE THREAD

**Issue by LorenzosSummer** [ros2/cartographer#19]
i readed the https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html
it`s only build for catkin, i don`t know how to build cartographer_ros with ros2-foxy.
and is the 2D demo 3D demo support for foxy？

**Comment by clalancette** [comment]
The easiest way to use cartographer in Foxy is to just install the pre-built packages:

```
sudo apt-get install ros-foxy-cartographer
```

If you really want to build it from source, then you'll need to clone this repository and built it against Foxy, something like:
```
mkdir -p cart_ws/src
cd cart_ws/src
git clone https://github.com/ros2/cartographer
cd ..
. /opt/ros/foxy/setup.bash
colcon build
```

I've never tried the 2D or 3D demo on Foxy, but there are very minimal changes between this version of cartographer and upstream.  So if it works on upstream, it probably works here.

Finally, please ask questions like this on https://answers.ros.org.  That way they are all in one place and are searchable.  I'm going to close this issue out.
