### ISSUE TITLE
ros launch

### ISSUE THREAD

**Issue by qitianyi** [ros2/cartographer#21]
I used the launcher's launch file on ros2 foxy, but prompted the following error
![1651736137(1)](https://user-images.githubusercontent.com/22910296/166880148-9003e993-56a4-4f6d-87fa-655545e50ccb.png)

![1651736085(1)](https://user-images.githubusercontent.com/22910296/166880036-7134e95d-fe08-4015-84f9-1ee99c8560d9.png)

**Comment by clalancette** [comment]
These launch files were never ported to ROS 2, which is why you are seeing the error.  If you'd like to attempt it, I'd be happy to review.

**Comment by alvaropascuaI** [comment]
Hi @qitianyi, have you been able to start it and if so, how? I have managed to do the colcon build of the package but I don't know how to continue

**Comment by clalancette** [comment]
Actually, looking at it further, this is reported on the wrong repository.  This should be on https://github.com/ros2/cartographer_ros

Given that, and the age of this issue, I'm going to close it out.  Feel free to reopen over there if you are still interested.
