### ISSUE TITLE
node arguments not set

### ISSUE THREAD

**Issue by praetorianer777** [ros2/cartographer#22]
Hello,

I try to start cartographer in a launch.py file. I set the parameters for configuration_dir and -basename, but on startup cartographer gives me an error that the arguments are missing, what am I doing wrong?

`[cartographer_node-1] F0725 18:46:28.791841  2041 node_main.cc:91] Check failed: !FLAGS_configuration_directory.empty() -configuration_directory is missing.
[cartographer_node-1] *** Check failure stack trace: ***
[cartographer_node-1]     @     0x7f3252a3f1c3  google::LogMessage::Fail()
[cartographer_node-1]     @     0x7f3252a4425b  google::LogMessage::SendToLog()
[cartographer_node-1]     @     0x7f3252a3eebf  google::LogMessage::Flush()
[cartographer_node-1]     @     0x7f3252a3f6ef  google::LogMessageFatal::~LogMessageFatal()
[cartographer_node-1]     @     0x557414ec78ff  (unknown)
[cartographer_node-1]     @     0x7f3251f9b083  __libc_start_main
[cartographer_node-1]     @     0x557414ec9aae  (unknown)
[ERROR] [cartographer_node-1]: process has died [pid 2041, exit code -6, cmd '/opt/ros/foxy/lib/cartographer_ros/cartographer_node --ros-args -r __node:=cartographer --params-file /tmp/launch_params_1359tugn'].`

`
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='cartographer_ros',
            executable='cartographer_node',
            name='cartographer',
            parameters=[{
                "configuration_directory": '/home/steve/carto_mapper',
                "configuration_basename": 'x4.lua',
            }]
        ),
        Node(
            package='cartographer_ros',
            executable='occupancy_grid_node',
            name='grid',
            parameters=[{
                "resolution": 0.05,
                "publish_period_sec": 1.0,
            }]
        ),
    ])`

**Comment by clalancette** [comment]
Your launch file is setting parameters, but cartographer expects those to be arguments.  See https://github.com/ros2/geometry2/blob/2687a3543bf61481b06dcf37839c7e92bed85d2e/test_tf2/test/test_buffer_client.launch.py#L20-L25 for an example.

In the future, please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  I'm going to close this out.
