### ISSUE TITLE
Current version demands gflags

### ISSUE THREAD

**Issue by bergercookie** [ros2/cartographer#8]
The google version of cartographer demands only the suitesparse component of Ceres. However, this fork also demands `gflags`. However, that's not stated in any CMake file, thus it brakes on the inclusion of the corresponding header if ceres doesn't compile with gflags.

See https://github.com/ros2/cartographer/blob/ros2/cartographer/io/migrate_serialization_format_main.cc

**Comment by clalancette** [comment]
I guess I don't really understand.  This is a direct fork of the upstream cartographer, pinned to release 1.0.0.  The only differences from upstream is in package.xml, where I:

* Changed the maintainers (so upstream wouldn't get mail about this fork)
* Switched this from a catkin to a pure cmake project
* Changed the ceres dependency to be able to use the name we use from rosdep

So I'm not sure where the extra dependency comes from, unless it is missing from upstream.

**Comment by bergercookie** [comment]
Indeed, that's my bad.

Probably though this issue has been fixed on the upstream since the `migrate_serialization_format_main.cc` doesn't exist anymore (there are some `*_migration` files but they don't directly include `glflags` anywhere in their code.

**Comment by clalancette** [comment]
Since we've updated to a newer cartographer, this probably isn't a problem.  I'm going to close this out for now.
