### ISSUE TITLE
[Windows][ROS2] Consider rebasing to newer version of cartographer for Windows build

### ISSUE THREAD

**Issue by seanyen** [ros2/cartographer#9]
In https://github.com/googlecartographer/cartographer, there are many activities after this ROS2 fork. For example, https://github.com/googlecartographer/cartographer/pull/1463 is a milestone changes for enabling Windows build. It would be nice to consider rebasing this ROS2 to take advantage from the parent fork.

**Comment by clalancette** [comment]
I'm reluctant to update this fork to a newer version until upstream cartographer does another tag/release.  As far as I can tell, that hasn't happened yet.  Once that happens, feel free to comment here and we can think about doing an update.
